fix: zsac errors and asg target variable name

diff --git a/examples/zsac b/examples/zsac
--- a/examples/zsac
+++ b/examples/zsac
@@ -304,7 +304,7 @@ done
 if [[ "$dtype" != *"zpa"* ]]; then
 read -r -p "Enter AC Provisioning Key (E.g. 3|api.private.zscaler.com|<string>): " ac_prov_key
 echo "Provisioning Key entered is: $ac_prov_key"
-echo "export TF_VAR_ac_prov_key=${ac_prov_key}" >> .zsacrc
+echo "export TF_VAR_ac_prov_key='${ac_prov_key}'" >> .zsacrc
 fi
 
 ac_count_default=2
@@ -359,19 +359,6 @@ max_size=${max_size_input:-$max_size_default}
     fi
 done
 
-az_count_default=2
-    read -r -p "Enter how many Availability Zone subnets [1-3] to deploy across? [Default=$az_count_default]: " az_count_input
-az_count=${az_count_input:-$az_count_default}
-if ((az_count >= 1 && az_count <= 3)); then
-    echo "${dtype} will deploy ${ac_count} App Connectors across ${az_count} Availabiliy Zone subnets in ${aws_region}"
-    echo "export TF_VAR_az_count=${az_count}" >> .zsacrc
-else
-    echo "invalid az_count value. Must be a number between 1 and 3"
-    echo "Delete .zsacrc file and re-run zsac up..."
-    exit 1
-fi  
-fi
-
 target_cpu_util_value_default=50
 while [[ "$dtype" == *"asg"* ]]; do
     read -r -p "Enter desired ASG Target Tracking CPU Utilization target [Default=$target_cpu_util_value_default]: " target_cpu_util_value_input
@@ -389,6 +376,17 @@ target_cpu_util_value=${target_cpu_util_value_input:-$target_cpu_util_value_defa
     fi
 done
 
+az_count_default=2
+    read -r -p "Enter how many Availability Zone subnets [1-3] to deploy across? [Default=$az_count_default]: " az_count_input
+az_count=${az_count_input:-$az_count_default}
+if ((az_count >= 1 && az_count <= 3)); then
+    echo "${dtype} will deploy ${ac_count} App Connectors across ${az_count} Availabiliy Zone subnets in ${aws_region}"
+    echo "export TF_VAR_az_count=${az_count}" >> .zsacrc
+else
+    echo "invalid az_count value. Must be a number between 1 and 3"
+    echo "Delete .zsacrc file and re-run zsac up..."
+    exit 1
+fi  
 
 while [[ "$dtype" == *"asg"* ]]; do
     read -r -p "Do you want Warm Pool enabled on the Autoscaling Group? (yes/no): " warm_pool_response
@@ -477,7 +475,7 @@ case $reuse_on_scale_in_response in
     esac
 done 
 fi
-
+fi
 
 # add local bin directory to PATH
 if ! grep -Fxq "export PATH=\${PATH}:\${PWD}/bin" .zsacrc; then
